name = "fapleaks"
main = "worker.js"
compatibility_date = "2026-05-06"

[vars]
ORIGIN = "https://crystalfallsventures.click"

[[routes]]
pattern = "crystalfallsventures.click/*"
zone_name = "crystalfallsventures.click"
